#!/bin/bash
#$1 is the list of ipv6 link local
#$2 is the name of the file to copy
#$3 destination path
if="eth0"
cat $1 | while read -r line
do
    ip="$line"
    echo $ip
    echo|ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$ip "mkdir -p $3"
    echo|scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $2 root@[$ip]:$3
done
