#!/bin/bash
#$1 is the list of ipv6 link local
#$2 is the name of the packet to install
#$3 (optional) pakage to remove 
if="eth0"
cat $1 | while read -r line
do
    ip="$line"%"$if"
    scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null wbm11/packages/$2 root@[$ip]:/tmp/
    if [ "$3" != "" ]; then
      echo| ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$ip "opkg remove $3"
    fi
    echo| ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$ip "opkg --force-reinstall install /tmp/$2 && rm /tmp/$2"
    echo "packet deployed on $ip"
done
