#!/bin/bash

if="eth0"
cat $1 | while read -r line
do
    ip="$line"%"$if"
    echo scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null config-wdr/wireless root@$ip:/etc/config/
    scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null config-wdr/wireless root@[$ip]:/etc/config/
    echo "$ip wireless configuration updated"
done
