#!/bin/bash

if="enxa0cec817ade8"
cat $1 | while read -r line
do
    ip="$line"
    scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null config-wdr/wireless root@$ip:/etc/config/
    echo "$ip wireless configuration updated"
done
